[package]
name = "polako_flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polako_constructivism = { path = "../polako_constructivism"}
polako_input = { path = "../polako_input"}
bevy = "0.11.3"